import Link from "next/link";
import { Icon } from "@/components/ui/Icon";
import { site } from "@/lib/site";
import { authorCredentialFor, stableIndex } from "@/lib/trust-copy";
import type { RegisteredTool, ToolCategory } from "@/lib/tool-types";

/**
 * The tool equivalent of `PlatformNote` and `PromptByline`. A separate
 * component rather than a generalised one: `Category` and `ToolCategory`
 * are structurally close but not identical, and duplicating roughly forty
 * lines here is cheaper than a shared type that has to keep both in sync.
 */
const PLATFORM_INTROS = (count: string) => [
  (name: string) =>
    `${name} also runs ${count} free tools, computed entirely in your browser rather than generated by a model. Each one names what it will not do, and none of them upload anything you enter.`,
  (name: string) =>
    `Alongside its prompts, ${name} runs ${count} tools that compute a real answer client side. No account, no server call, no invented data standing in for yours.`,
  (name: string) =>
    `${count} tools live on ${name}, each one a working calculator or generator rather than a suggestion. Every input stays in your browser and every result shows its working.`,
  (name: string) =>
    `This tool is one of ${count} on ${name}, all computed locally rather than sent to a model. Where a real fact would go stale, like a tax rate, the tool asks you for it instead of guessing.`,
  (name: string) =>
    `${name} pairs its prompt directory with ${count} tools that actually compute something, checkable and reproducible, run entirely in this tab.`,
];

export function ToolPlatformNote({
  tool,
  category,
}: {
  tool: RegisteredTool;
  category: ToolCategory;
}) {
  const count = "94";
  const variants = PLATFORM_INTROS(count);
  const intro = variants[stableIndex(`tool:${tool.slug}`, variants.length)](site.name);

  return (
    <section
      aria-labelledby="about-platform"
      className="mt-14 rounded-lg border border-hairline bg-surface-2/40 p-6"
    >
      <h2 id="about-platform" className="text-[1.0625rem] font-semibold text-ink">
        About {site.name}
      </h2>

      <p className="mt-2.5 text-[0.9375rem] leading-relaxed text-ink-muted">{intro}</p>

      <p className="mt-3 text-[0.9375rem] leading-relaxed text-ink-muted">{category.intro}</p>

      <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2">
        <Link
          href={`/tools/category/${category.slug}`}
          className="inline-flex items-center gap-1.5 text-[0.8125rem] font-medium text-signal-bright"
        >
          <Icon name="arrow-right" size={13} />
          All {category.name.toLowerCase()} tools
        </Link>
        <Link
          href="/tools"
          className="inline-flex items-center gap-1.5 text-[0.8125rem] font-medium text-signal-bright"
        >
          <Icon name="compass" size={13} />
          Browse every tool
        </Link>
        <Link
          href="/explore"
          className="inline-flex items-center gap-1.5 text-[0.8125rem] font-medium text-signal-bright"
        >
          <Icon name="info" size={13} />
          Browse the prompt directory
        </Link>
      </div>

      <p className="mt-4 border-t border-hairline pt-3 text-[0.75rem] text-ink-faint">
        This page covers the {tool.seo.primaryKeyword}. Last reviewed{" "}
        {new Date(tool.updated).toLocaleDateString("en-GB", {
          day: "numeric",
          month: "long",
          year: "numeric",
        })}
        .
      </p>
    </section>
  );
}

export function ToolByline({ tool }: { tool: RegisteredTool }) {
  return (
    <div className="mx-auto mt-6 max-w-2xl rounded-lg border border-hairline bg-surface-2/30 px-5 py-4 text-left">
      <div className="flex flex-wrap items-baseline gap-x-2 gap-y-1">
        <span className="text-[0.875rem] font-medium text-ink">{tool.eeat.author}</span>
        <span className="text-[0.8125rem] text-ink-subtle">{authorCredentialFor(`tool:${tool.slug}`)}</span>
      </div>

      <p className="mt-2 text-[0.8125rem] leading-relaxed text-ink-muted">
        <span className="font-medium text-ink">Built on {tool.eeat.testedOn.join(", ")}. </span>
        {tool.eeat.testingNote}
      </p>
    </div>
  );
}
