import Head from 'next/head'
import styles from '@/styles/Home.module.css' // We'll create this file in the next step

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1>Welcome to My Landing Page</h1>
        <nav>
          <ul className={styles.navList}>
            <li className={styles.navItem}><a href="#">Home</a></li>
            <li className={styles.navItem}><a href="#">About</a></li>
            <li className={styles.navItem}><a href="#">Services</a></li>
            <li className={styles.navItem}><a href="#">Contact</a></li>
          </ul>
        </nav>
      </header>

      <main className={styles.main}>
        <section className={styles.hero}>
          <h2>Discover Amazing Things</h2>
          <p>This is a hero section where you can showcase your main product or service.</p>
          <button className={styles.ctaButton}>Learn More</button>
        </section>

        <section className={styles.features}>
          {/* Placeholder for feature sections */}
          <div className={styles.feature}>
            <h3>Feature 1</h3>
            <p>Description of feature 1.</p>
          </div>
          <div className={styles.feature}>
            <h3>Feature 2</h3>
            <p>Description of feature 2.</p>
          </div>
          <div className={styles.feature}>
            <h3>Feature 3</h3>
            <p>Description of feature 3.</p>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <p>&copy; {new Date().getFullYear()} My Landing Page. All rights reserved.</p>
      </footer>
    </div>
  )
}
